# Generated by Django 3.1.3 on 2020-12-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201208_2126'),
        ('authentication', '0002_auto_20201207_2150'),
    ]

    operations = [
    ]
