name: music_karaoke

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: migrations
      run: |
        python music_karaoke/manage.py makemigrations
        python music_karaoke/manage.py migrate
    - name: run tests
      working-directory: ./music_karaoke
      run: python manage.py test tests
